### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by DominiqueMakowski** [hddm-devs/hddm#41]
Hey, 
I can't install hddm using pip on python 3.5.2.2, windows 10 64x (I'm using WinPyhon).

Do you have any idea on why is this erroring?

Thanks a lot!

Here's the full error log:

```
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,>=1.5.6 in c:\users\dom\desktop\winpython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages (from matplotlib>=1.0.0->kabuki>=0.6.0->HDDM==0.6.1)
Requirement already satisfied: cycler in c:\users\dom\desktop\winpython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages (from matplotlib>=1.0.0->kabuki>=0.6.0->HDDM==0.6.1)
Installing collected packages: HDDM
  Running setup.py install for HDDM ... error
    Complete output from command C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-
3.5.2.amd64\python.exe -u -c "import setuptools, 
tokenize;__file__='C:\\Users\\Dom\\AppData\\Local\\Temp\\pip-eaetvo7a-
build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', 
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Dom\AppData\Local\Temp\pip-
uc4akrza-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\hddm
    copying hddm\diag.py -> build\lib.win-amd64-3.5\hddm
    copying hddm\generate.py -> build\lib.win-amd64-3.5\hddm
    copying hddm\likelihoods.py -> build\lib.win-amd64-3.5\hddm
    copying hddm\MPLTraits.py -> build\lib.win-amd64-3.5\hddm
    copying hddm\MPLTraits_qt.py -> build\lib.win-amd64-3.5\hddm
    copying hddm\utils.py -> build\lib.win-amd64-3.5\hddm
    copying hddm\__init__.py -> build\lib.win-amd64-3.5\hddm
    creating build\lib.win-amd64-3.5\hddm\tests
    copying hddm\tests\benchmark.py -> build\lib.win-amd64-3.5\hddm\tests
    copying hddm\tests\matlab_values.py -> build\lib.win-amd64-3.5\hddm\tests
    copying hddm\tests\test_generate.py -> build\lib.win-amd64-3.5\hddm\tests
    copying hddm\tests\test_likelihoods.py -> build\lib.win-amd64-3.5\hddm\tests
    copying hddm\tests\test_models.py -> build\lib.win-amd64-3.5\hddm\tests
    copying hddm\tests\test_optimization.py -> build\lib.win-amd64-3.5\hddm\tests
    copying hddm\tests\__init__.py -> build\lib.win-amd64-3.5\hddm\tests
    creating build\lib.win-amd64-3.5\hddm\models
    copying hddm\models\base.py -> build\lib.win-amd64-3.5\hddm\models
    copying hddm\models\hddm_info.py -> build\lib.win-amd64-3.5\hddm\models
    copying hddm\models\hddm_regression.py -> build\lib.win-amd64-3.5\hddm\models
    copying hddm\models\hddm_stimcoding.py -> build\lib.win-amd64-3.5\hddm\models
    copying hddm\models\hddm_transformed.py -> build\lib.win-amd64-3.5\hddm\models
    copying hddm\models\hddm_truncated.py -> build\lib.win-amd64-3.5\hddm\models
    copying hddm\models\__init__.py -> build\lib.win-amd64-3.5\hddm\models
    creating build\lib.win-amd64-3.5\hddm\examples
    copying hddm\examples\plot_posterior_quantiles.py -> build\lib.win-amd64-3.5\hddm\examples
    copying hddm\examples\simple_model.py -> build\lib.win-amd64-3.5\hddm\examples
    copying hddm\examples\__init__.py -> build\lib.win-amd64-3.5\hddm\examples
    copying hddm\examples\cavanagh_theta_nn.csv -> build\lib.win-amd64-3.5\hddm\examples
    copying hddm\examples\simple_difficulty.csv -> build\lib.win-amd64-3.5\hddm\examples
    copying hddm\examples\simple_subjs_difficulty.csv -> build\lib.win-amd64-3.5\hddm\examples
    copying hddm\examples\simple_subjs_difficulty_single.csv -> build\lib.win-amd64-3.5\hddm\examples
    copying hddm\examples\simple_difficulty.conf -> build\lib.win-amd64-3.5\hddm\examples
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Dom\AppData\Local\Temp\pip-eaetvo7a-build\setup.py", line 39, in <module>
        ext_modules = ext_modules
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages\setuptools\command\build_ext.py", line 68, in run
        _build_ext.run(self)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages\Cython\Distutils\build_ext.py", line 164, in run
        _build_ext.build_ext.run(self)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\command\build_ext.py", line 307, in run
        force=self.force)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\ccompiler.py", line 1031, in new_compiler
        return klass(None, dry_run, force)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\cygwinccompiler.py", line 282, in __init__
        CygwinCCompiler.__init__ (self, verbose, dry_run, force)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\distutils\cygwinccompiler.py", line 126, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: unorderable types: NoneType() >= str()

    ----------------------------------------
Command "C:\Users\Dom\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\python.exe -u -c 
"import setuptools, tokenize;__file__='C:\\Users\\Dom\\AppData\\Local\\Temp\\pip-eaetvo7a-
build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', 
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Dom\AppData\Local\Temp\pip-
uc4akrza-record\install-record.txt --single-version-externally-managed --compile" failed with error code 
1 in C:\Users\Dom\AppData\Local\Temp\pip-eaetvo7a-build\
```

**Comment by josemceb** [comment]
I'm having the same issue on my Mac:

`Command "//anaconda/envs/Py3.5/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_k/vhkrrz4d6nl6zgzw_hmd4sxh0000gn/T/pip-build-nvl8n3d2/hddm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/_k/vhkrrz4d6nl6zgzw_hmd4sxh0000gn/T/pip-x493098f-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_k/vhkrrz4d6nl6zgzw_hmd4sxh0000gn/T/pip-build-nvl8n3d2/hddm/`

**Comment by twiecki** [comment]
@josemceb can you post the full output?

**Comment by josemceb** [comment]
Apologies, here it is!

```
Collecting HDDM
  Using cached HDDM-0.6.1.tar.gz
Requirement already satisfied: NumPy>=1.6.0 in /anaconda/envs/Py3.5/lib/python3.5/site-packages (from HDDM)
Requirement already satisfied: SciPy>=0.6.0 in /anaconda/envs/Py3.5/lib/python3.5/site-packages (from HDDM)
Requirement already satisfied: kabuki>=0.6.0 in /anaconda/envs/Py3.5/lib/python3.5/site-packages (from HDDM)
Requirement already satisfied: PyMC>=2.3.3 in /anaconda/envs/Py3.5/lib/python3.5/site-packages (from HDDM)
Requirement already satisfied: pandas>=0.12.0 in /anaconda/envs/Py3.5/lib/python3.5/site-packages (from HDDM)
Requirement already satisfied: patsy in /anaconda/envs/Py3.5/lib/python3.5/site-packages (from HDDM)
Requirement already satisfied: matplotlib>=1.0.0 in /anaconda/envs/Py3.5/lib/python3.5/site-packages (from kabuki>=0.6.0->HDDM)
Requirement already satisfied: pytz>=2011k in /anaconda/envs/Py3.5/lib/python3.5/site-packages (from pandas>=0.12.0->HDDM)
Requirement already satisfied: python-dateutil>=2 in /anaconda/envs/Py3.5/lib/python3.5/site-packages (from pandas>=0.12.0->HDDM)
Requirement already satisfied: six in /anaconda/envs/Py3.5/lib/python3.5/site-packages (from patsy->HDDM)
Requirement already satisfied: cycler>=0.10 in /anaconda/envs/Py3.5/lib/python3.5/site-packages (from matplotlib>=1.0.0->kabuki>=0.6.0->HDDM)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /anaconda/envs/Py3.5/lib/python3.5/site-packages (from matplotlib>=1.0.0->kabuki>=0.6.0->HDDM)
Building wheels for collected packages: HDDM
  Running setup.py bdist_wheel for HDDM ... error
  Complete output from command //anaconda/envs/Py3.5/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_k/vhkrrz4d6nl6zgzw_hmd4sxh0000gn/T/pip-build-f542ng8s/HDDM/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/_k/vhkrrz4d6nl6zgzw_hmd4sxh0000gn/T/tmp8dpdje4mpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-3.5
  creating build/lib.macosx-10.6-x86_64-3.5/hddm
  copying hddm/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
  copying hddm/diag.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
  copying hddm/generate.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
  copying hddm/likelihoods.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
  copying hddm/MPLTraits.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
  copying hddm/MPLTraits_qt.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
  copying hddm/utils.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
  creating build/lib.macosx-10.6-x86_64-3.5/hddm/tests
  copying hddm/tests/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
  copying hddm/tests/benchmark.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
  copying hddm/tests/matlab_values.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
  copying hddm/tests/test_generate.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
  copying hddm/tests/test_likelihoods.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
  copying hddm/tests/test_models.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
  copying hddm/tests/test_optimization.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
  creating build/lib.macosx-10.6-x86_64-3.5/hddm/models
  copying hddm/models/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
  copying hddm/models/base.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
  copying hddm/models/hddm_info.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
  copying hddm/models/hddm_regression.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
  copying hddm/models/hddm_stimcoding.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
  copying hddm/models/hddm_transformed.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
  copying hddm/models/hddm_truncated.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
  creating build/lib.macosx-10.6-x86_64-3.5/hddm/examples
  copying hddm/examples/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
  copying hddm/examples/plot_posterior_quantiles.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
  copying hddm/examples/postpred.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
  copying hddm/examples/simple_model.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
  copying hddm/examples/cavanagh_theta_nn.csv -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
  copying hddm/examples/simple_difficulty.csv -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
  copying hddm/examples/simple_subjs_difficulty.csv -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
  copying hddm/examples/simple_subjs_difficulty_single.csv -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
  copying hddm/examples/simple_difficulty.conf -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
  running build_ext
  building 'wfpt' extension
  creating build/temp.macosx-10.6-x86_64-3.5
  creating build/temp.macosx-10.6-x86_64-3.5/src
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda/envs/Py3.5/include -arch x86_64 -I//anaconda/envs/Py3.5/lib/python3.5/site-packages/numpy/core/include -I//anaconda/envs/Py3.5/include/python3.5m -c src/wfpt.c -o build/temp.macosx-10.6-x86_64-3.5/src/wfpt.o
  clang: error: no such file or directory: 'src/wfpt.c'
  clang: error: no input files
  error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for HDDM
  Running setup.py clean for HDDM
Failed to build HDDM
Installing collected packages: HDDM
  Running setup.py install for HDDM ... error
    Complete output from command //anaconda/envs/Py3.5/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_k/vhkrrz4d6nl6zgzw_hmd4sxh0000gn/T/pip-build-f542ng8s/HDDM/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/_k/vhkrrz4d6nl6zgzw_hmd4sxh0000gn/T/pip-baz18mcy-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-x86_64-3.5
    creating build/lib.macosx-10.6-x86_64-3.5/hddm
    copying hddm/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
    copying hddm/diag.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
    copying hddm/generate.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
    copying hddm/likelihoods.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
    copying hddm/MPLTraits.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
    copying hddm/MPLTraits_qt.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
    copying hddm/utils.py -> build/lib.macosx-10.6-x86_64-3.5/hddm
    creating build/lib.macosx-10.6-x86_64-3.5/hddm/tests
    copying hddm/tests/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
    copying hddm/tests/benchmark.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
    copying hddm/tests/matlab_values.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
    copying hddm/tests/test_generate.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
    copying hddm/tests/test_likelihoods.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
    copying hddm/tests/test_models.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
    copying hddm/tests/test_optimization.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/tests
    creating build/lib.macosx-10.6-x86_64-3.5/hddm/models
    copying hddm/models/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
    copying hddm/models/base.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
    copying hddm/models/hddm_info.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
    copying hddm/models/hddm_regression.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
    copying hddm/models/hddm_stimcoding.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
    copying hddm/models/hddm_transformed.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
    copying hddm/models/hddm_truncated.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/models
    creating build/lib.macosx-10.6-x86_64-3.5/hddm/examples
    copying hddm/examples/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
    copying hddm/examples/plot_posterior_quantiles.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
    copying hddm/examples/postpred.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
    copying hddm/examples/simple_model.py -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
    copying hddm/examples/cavanagh_theta_nn.csv -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
    copying hddm/examples/simple_difficulty.csv -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
    copying hddm/examples/simple_subjs_difficulty.csv -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
    copying hddm/examples/simple_subjs_difficulty_single.csv -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
    copying hddm/examples/simple_difficulty.conf -> build/lib.macosx-10.6-x86_64-3.5/hddm/examples
    running build_ext
    building 'wfpt' extension
    creating build/temp.macosx-10.6-x86_64-3.5
    creating build/temp.macosx-10.6-x86_64-3.5/src
    /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda/envs/Py3.5/include -arch x86_64 -I//anaconda/envs/Py3.5/lib/python3.5/site-packages/numpy/core/include -I//anaconda/envs/Py3.5/include/python3.5m -c src/wfpt.c -o build/temp.macosx-10.6-x86_64-3.5/src/wfpt.o
    clang: error: no such file or directory: 'src/wfpt.c'
    clang: error: no input files
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "//anaconda/envs/Py3.5/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_k/vhkrrz4d6nl6zgzw_hmd4sxh0000gn/T/pip-build-f542ng8s/HDDM/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/_k/vhkrrz4d6nl6zgzw_hmd4sxh0000gn/T/pip-baz18mcy-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_k/vhkrrz4d6nl6zgzw_hmd4sxh0000gn/T/pip-build-f542ng8s/HDDM/
```

**Comment by ronimaimon** [comment]
I have the exact same issue on my Mac. 
  clang: error: no such file or directory: 'src/wfpt.c'

Did anyone find a way around it?

**Comment by twiecki** [comment]
Why are you not installing using anaconda?

**Comment by ronimaimon** [comment]
I can install anaconda specifically for this but was hoping to have hddm
installed together with the rest of my python packages..

**Comment by sammosummo** [comment]
Unfortunately having one big python environment for all your needs is not very feasible. This is one of the major gripes about python for many people. I would recommend switching to anaconda permanently and creating virtual envs for your disparate projects. Personally I have a virtual env just for hddm related work.

--
Samuel R. Mathias, Ph.D.
Associate Research Scientist (ARS)
Neurocognition, Neurocomputation and Neurogenetics (n3) Division
Yale University School of Medicine
40 Temple Street, Room 694
New Haven CT 06510
http://www.srmathias.com
________________________________

**Comment by twiecki** [comment]
Yes, that's the best approach. Note that conda environments also work quite
well.

**Comment by arthurprat** [comment]
I have run in the same problem and I wanted to keep my pip workflow.

Apparently `setup.py` tries to install wfpt using Cython and `'src/wfpt.pyx'`, but if it cannot find Cython, it will try to use `'src/wfpt.c'`. This file is not there, so it fails.
Hence my solution was to install Cython using:
`pip install Cython`

So far it is working. I hope nothing is broken under the hood...

**Comment by birkin** [comment]
I too had issues installing this in my 'normal' development setup of pip-installing into a virtual-environment on my mac. I wrote up [notes](https://gist.github.com/birkin/3b17a11ccbfa512a59565296ce4c7ff4) detailing steps that worked for me.

**Comment by cgc** [comment]
Installing Cython first with `pip install Cython` resolved this issue for me. Might be worth modifying the pip documentation to recommend installing Cython in addition to the other packages? I'm happy to draft that pull request.
